media:
  input: public
  output: /
content:
  - name: faq
    label: FAQ Collection
    type: collection
    path: src/content/faq
    fields: 
      - name: title  
        label: Title
        type: string 
      - name: faq-section
        label: FAQ Section ❔
        type: object
        fields: 
          - name: headline
            label: Headline
            type: string
          - name: faq
            list: true
            label: FAQ
            type: object
            fields: 
              - name: q
                label: Q
                type: string
              - name: a
                label: A
                type: text
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, date]
    fields:
      - { name: author, label: Author, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: body, label: Body, type: rich-text }
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
      - name: faq-section
        label: FAQ Section ❔
        type: reference
        options:
          collection: faq
          value: "{id}"
      - name: contact
        label: Contact information
        type: object
        fields:
          - name: first_name
            label: First name
            type: string
          - name: last_name
            label: Last name
            type: string
          - name: email
            label: Email address
            type: string
          - name: phone
            label: Phone number
            type: string
  - name: about
    label: About page
    type: file
    path: src/content/about.md
    fields:
      - { name: title, label: Title, type: string }
      - {
          name: body,
          label: Body,
          type: rich-text,
          options: { input: public/assets, output: /assets },
        }
