media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, date]
    fields:
      - { name: author, label: Author, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: body, label: Body, type: rich-text }
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: about
    label: About page
    type: file
    path: src/content/about.md
    fields:
      - { name: title, label: Title, type: string }
      - {
          name: body,
          label: Body,
          type: rich-text,
          options: { input: public/assets, output: /assets },
        }
